# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  database: journal_app_development
  username: rkbart          
  password: password123
  host: localhost

test:
  <<: *default
  database: journal_app_test
  username: rkbart          
  password: password123
  host: localhost

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV["PGDATABASE"] %>
    username: <%= ENV["PGUSER"] %>
    password: <%= ENV["PGPASSWORD"] %>
    host: <%= ENV["PGHOST"] %>
    port: 5432
  cache:
    <<: *primary_production
    database: <%= ENV["PGDATABASE"] %>_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV["PGDATABASE"] %>_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV["PGDATABASE"] %>_cable
    migrations_paths: db/cable_migrate