default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  database: journal_app_development
  username: rkbart          
  password: password123
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: journal_app_test
  username: rkbart
  password: password123
  host: localhost

# test:
#   <<: *default
#   database: journal_app_test
#   username: rkbart          
#   password: password123
#   host: localhost

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV["PGDATABASE"] %>
    username: <%= ENV["PGUSER"] %>
    password: <%= ENV["PGPASSWORD"] %>
    host: <%= ENV["PGHOST"] %>
    port: 5432
  cache:
    <<: *primary_production
    database: <%= ENV["PGDATABASE"] %>_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV["PGDATABASE"] %>_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV["PGDATABASE"] %>_cable
    migrations_paths: db/cable_migrate